### ISSUE TITLE
Evaluation of totalEvolutions always returns NaN

### ISSUE THREAD

**Issue by farmerau** [ayechonk/pokemon-evolution-trainer#1]
The error can be resolved in one of three ways:

- Removing the empty object with no parameters in pokemon.json
- Setting the empty object with values that won't break operations
- Performing an array splice on the pokemon object.

Removing the object makes sense **if** we're never going to reference `pokemon[i]`.

If we care about counting from one, initializing the empty (first) object is our best bet, otherwise we'll need to perform an array splice anytime we reference the pokemon object, which is just as good as removing the object from the array.

What do you think @ayechonk ?

**Comment by ayechonk** [comment]
@farmerau I'm thinking just make an empty "pokemon" instead of empty object.  We are generally going to filter out count > 0 or something.

**Comment by ayechonk** [comment]
I just decided to remove the actual blank object. Makes no sense to actually have one.
