### ISSUE TITLE
Handling candy reduction during evolution seems to be calculated wrong.

### ISSUE THREAD

**Issue by farmerau** [ayechonk/pokemon-evolution-trainer#5]
I could be wrong, but in the evolvePokemon function it seems that we're subtracting a single candy of the type of candy necessary instead of the cost needed to evolve the pokemon. Feel free to correct me if wrong.

**Comment by ayechonk** [comment]
Yes you're right. You are more than welcome to fix shit

**Comment by ryanwhetstone** [comment]
Dorks! 😀 How'd I get in on this?

**Comment by ayechonk** [comment]
No need for your sass

**Comment by farmerau** [comment]
Resolved.
